// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PociagDoZyskow.DataAccess.Contexts;

namespace PociagDoZyskow.DataAccess.Migrations
{
    [DbContext(typeof(StockExchangeContext))]
    [Migration("20200722190520_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PociagDoZyskow.DataAccess.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ExchangeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnName("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeId");

                    b.ToTable("Company","stock");
                });

            modelBuilder.Entity("PociagDoZyskow.DataAccess.Entities.Stock.Exchange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnName("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exchange","stock");
                });

            modelBuilder.Entity("PociagDoZyskow.DataAccess.Entities.Stock.Record", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<decimal>("HighestPrice")
                        .HasColumnName("HighestPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LastPrice")
                        .HasColumnName("LastPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LastTransactionTime")
                        .HasColumnName("LastTransactionTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("LastTransactionVolume")
                        .HasColumnName("LastTransactionVolume")
                        .HasColumnType("int");

                    b.Property<decimal>("LowestPrice")
                        .HasColumnName("LowestPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OpenPrice")
                        .HasColumnName("OpenPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ReferencePrice")
                        .HasColumnName("ReferencePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalTransactionVolume")
                        .HasColumnName("TotalTransactionVolume")
                        .HasColumnType("int");

                    b.Property<int>("TransactionsCount")
                        .HasColumnName("TransactionsCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Record","stock");
                });

            modelBuilder.Entity("PociagDoZyskow.DataAccess.Entities.Company", b =>
                {
                    b.HasOne("PociagDoZyskow.DataAccess.Entities.Stock.Exchange", "Exchange")
                        .WithMany("Companies")
                        .HasForeignKey("ExchangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PociagDoZyskow.DataAccess.Entities.Stock.Record", b =>
                {
                    b.HasOne("PociagDoZyskow.DataAccess.Entities.Company", "Company")
                        .WithMany("Records")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
